package com.service.aiintegration.service.impl;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.service.aiintegration.common.Constants;
import com.service.aiintegration.dto.ChatRequestDTO;
import com.service.aiintegration.dto.ChatResponseDTO;
import com.service.aiintegration.service.AiService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.reactive.function.client.WebClient;

import java.util.List;
import java.util.Random;
import java.util.logging.Logger;
import java.util.stream.IntStream;

@Service
/** Implementation of the AiService interface for interacting with the Perplexity AI API.
 */
public class AiServiceImpl implements AiService {
    private final Logger log = Logger.getLogger(AiServiceImpl.class.getName());
    @Value("${perplexity.api.key}")
    private String apiKey;

    @Value("${perplexity.api.url}")
    private String apiUrl;

    @Value("${perplexity.ai.model}")
    private String modelName;

    private final WebClient webClient = WebClient.create();
    @Override
    @Transactional
    /** Method to ask the Perplexity API with a user prompt.
     * @param userPrompt The user's prompt.
     * @return ChatResponseDTO containing the response from the Perplexity API.
     */
    public ChatResponseDTO askPerplexity(String userPrompt) {
        log.info("Starting service method to ask Perplexity API with prompt: " + userPrompt);
        ChatRequestDTO request = new ChatRequestDTO(
                modelName, // Perplexity model name
                List.of(new ChatRequestDTO.Message(Constants.ROLE, userPrompt))
        );
        log.info("Constructed ChatRequestDTO: " + request);
        ChatResponseDTO response;
        try{
            response = webClient.post()
                    .uri(apiUrl)
                    .header("Authorization", "Bearer " + apiKey)
                    .header("Content-Type", "application/json")
                    .bodyValue(request)
                    .retrieve()
                    .bodyToMono(ChatResponseDTO.class)
                    .block();
        }
        catch (Exception e){
            log.info("Exception occurred while calling Perplexity API: " + e.getMessage());
            throw new RuntimeException(e.getMessage());
        }
        log.info("Service ends with ChatResponseDTO: " + response);
        return response;
    }
    @Override
    @Transactional
    /** Method to generate a mock embedding for the given text.
     * @param text The input text.
     * @return An array of Double representing the embedding.
     */
    public Double[] generateEmbedding(String text) {
        log.info("Starting service method to generate Embedding with text: " + text);
        Random random = new Random(text.hashCode()); // deterministic for same text
        return IntStream.range(Constants.ZERO, Constants.EIGHT) // 8-dim vector for demo
                .mapToDouble(i -> random.nextDouble())
                .boxed().toArray(Double[]::new);
    }
    @Override
    @Transactional
    /** Method to ask a question using provided context documents.
     * @param query The user's question.
     * @param contextDocs List of context documents.
     * @return The answer generated by the AI assistant.
     */
    public String ask(String query, List<String> contextDocs) {
        log.info("Starting service method to ask with query: " + query + ", contextDocs: " + contextDocs);
        String context = String.join("\n", contextDocs);
        String prompt = Constants.PROMPT_1.formatted(context, query);
        ChatRequestDTO request = new ChatRequestDTO(
                modelName, // Perplexity model name
                List.of(new ChatRequestDTO.Message(Constants.ROLE, prompt))
        );
        var response = webClient.post()
                .uri(apiUrl)
                .header("Authorization", "Bearer " + apiKey)
                .header("Content-Type", "application/json")
                .bodyValue(request)
                .retrieve()
                .bodyToMono(String.class)
                .block();
        if (response == null || response.isBlank()) {
            return Constants.EMPTY;
        }
        try {
            ObjectMapper mapper = new ObjectMapper();
            JsonNode root = mapper.readTree(response);
            JsonNode choices = root.path("choices");
            if (!choices.isArray() || choices.isEmpty()) {
                return Constants.EMPTY;
            }
            JsonNode messageNode = choices.get(Constants.ZERO).path("message");
            log.info("message: " + messageNode.asText());
            return messageNode.path("content").asText(Constants.EMPTY);
        } catch (Exception e) {
            log.info("Failed to parse completion: " + e.getMessage());
            throw new RuntimeException(e);
        }
    }
    @Override
    @Transactional
    /** Method to compute the cosine similarity between two vectors.
     * @param a First vector.
     * @param b Second vector.
     * @return Cosine similarity score.
     */
    public double cosineSimilarity(Double[] a, Double[] b) {
        if (a == null || b == null) {
            return Constants.NULL_CONFIDENCE_SCORE;
        }
        if (a.length == Constants.ZERO || b.length == Constants.ZERO) {
            return Constants.NULL_CONFIDENCE_SCORE;
        }

        int len = Math.min(a.length, b.length);
        double dot = Constants.NULL_CONFIDENCE_SCORE;
        double normA = Constants.NULL_CONFIDENCE_SCORE;
        double normB = Constants.NULL_CONFIDENCE_SCORE;

        for (int i = Constants.ZERO; i < len; i++) {
            double va = (a[i] == null) ? Constants.NULL_CONFIDENCE_SCORE : a[i];
            double vb = (b[i] == null) ? Constants.NULL_CONFIDENCE_SCORE : b[i];
            dot += va * vb;
            normA += va * va;
            normB += vb * vb;
        }

        if (normA == Constants.NULL_CONFIDENCE_SCORE || normB == Constants.NULL_CONFIDENCE_SCORE) {
            return Constants.NULL_CONFIDENCE_SCORE;
        }
        return dot / (Math.sqrt(normA) * Math.sqrt(normB));
    }
}
