package com.service.aiintegration.service;

import com.service.aiintegration.entity.Memory;

public interface RagService {
    /**
     * Save memory entry
     * @param type Type of memory
     * @param key Key for the memory
     * @param value Value of the memory
     * @return Saved Memory object
     */
    Memory saveMemory(String type, String key, String value);
    /**
     * Query the RAG system with user input
     * @param userQuery User's query string
     * @return Response generated by the RAG system
     */
    String query(String userQuery);
}
